name: Tarang74/README CI
description: README Continuous Integration for LaTeX QUT Notes.
author: Tarang Janawalkar

inputs:
  GITHUB_TOKEN:
    description: GitHub token
    required: true
  LEVEL_MACRO:
    description: Choose which level macro to use when enumerating contents
    default: section
    required: true

runs:
  using: node16
  main: dist/index.js

branding:
  icon: align-left
  color: gray-dark
